// Top popular assets (Stocks & Crypto) for auto-complete
// This list covers major S&P 500 companies, popular tech stocks, and top cryptocurrencies.

export const STATIC_ASSET_MAP: Record<string, string> = {
    // --- CRYPTO (Top 50+) ---
    'BITCOIN': 'BTC',
    'ETHEREUM': 'ETH',
    'TETHER': 'USDT',
    'BNB': 'BNB',
    'SOLANA': 'SOL',
    'XRP': 'XRP',
    'USDC': 'USDC',
    'CARDANO': 'ADA',
    'AVALANCHE': 'AVAX',
    'DOGECOIN': 'DOGE',
    'TRON': 'TRX',
    'POLKADOT': 'DOT',
    'CHAINLINK': 'LINK',
    'POLYGON': 'MATIC',
    'SHIBA INU': 'SHIB',
    'LITECOIN': 'LTC',
    'DAI': 'DAI',
    'BITCOIN CASH': 'BCH',
    'UNISWAP': 'UNI',
    'COSMOS': 'ATOM',
    'STELLAR': 'XLM',
    'MONERO': 'XMR',
    'ETHEREUM CLASSIC': 'ETC',
    'FILECOIN': 'FIL',
    'NEAR PROTOCOL': 'NEAR',
    'HBAR': 'HBAR',
    'APTOS': 'APT',
    'CRONOS': 'CRO',
    'VET': 'VET',
    'QUANT': 'QNT',
    'ALGORAND': 'ALGO',
    'GRT': 'GRT',
    'FANTOM': 'FTM',
    'SANDBOX': 'SAND',
    'DECENTRALAND': 'MANA',
    'RAVENCOIN': 'RVN',
    'AXIE INFINITY': 'AXS',
    'THETA': 'THETA',
    'AAVE': 'AAVE',
    'EOS': 'EOS',
    'TEZOS': 'XTZ',

    // --- STOCKS (Tech & Popular) ---
    'TESLA': 'TSLA',
    'APPLE': 'AAPL',
    'MICROSOFT': 'MSFT',
    'AMAZON': 'AMZN',
    'GOOGLE': 'GOOGL',
    'ALPHABET': 'GOOGL',
    'META': 'META',
    'FACEBOOK': 'META',
    'NVIDIA': 'NVDA',
    'BERKSHIRE HATHAWAY': 'BRK.B',
    'TSMC': 'TSM',
    'TENCENT': 'TCEHY',
    'VISA': 'V',
    'EXXON': 'XOM',
    'UNITEDHEALTH': 'UNH',
    'WALMART': 'WMT',
    'JPMORGAN': 'JPM',
    'JOHNSON & JOHNSON': 'JNJ',
    'MASTERCARD': 'MA',
    'PROCTER & GAMBLE': 'PG',
    'ELIG LILLY': 'LLY',
    'HOME DEPOT': 'HD',
    'CHEVRON': 'CVX',
    'MERCK': 'MRK',
    'ABBVIE': 'ABBV',
    'SAMSUNG': 'SSNLF',
    'COCA COLA': 'KO',
    'PEPSI': 'PEP',
    'COSTCO': 'COST',
    'BROADCOM': 'AVGO',
    'ORACLE': 'ORCL',
    'CISCO': 'CSCO',
    'MCDONALDS': 'MCD',
    'ADOBE': 'ADBE',
    'SALESFORCE': 'CRM',
    'DISNEY': 'DIS',
    'NETFLIX': 'NFLX',
    'AMD': 'AMD',
    'INTEL': 'INTC',
    'QUALCOMM': 'QCOM',
    'NIKE': 'NKE',
    'STARBUCKS': 'SBUX',
    'BOEING': 'BA',
    'AIRBNB': 'ABNB',
    'UBER': 'UBER',
    'PAYPAL': 'PYPL',
    'SQUARE': 'SQ',
    'BLOCK': 'SQ',
    'SHOPIFY': 'SHOP',
    'SONY': 'SONY',
    'TOYOTA': 'TM',
    'HONDA': 'HMC',
    'GENERAL MOTORS': 'GM',
    'FORD': 'F',
    'PALANTIR': 'PLTR',
    'SANDISK': 'WDC',
    'WESTERN DIGITAL': 'WDC',
    'GOLDMAN SACHS': 'GS',
    'MORGAN STANLEY': 'MS',
    'VIX': '^VIX',
    'SP500': 'SPY',
    'S&P 500': 'SPY',
    'NASDAQ': 'QQQ',
    'DOW JONES': 'DIA',
    'RUSSELL 2000': 'IWM',
    'GOLD': 'XAU',
    'ORO': 'XAU',
    'SILVER': 'XAG',
    'PLATA': 'XAG',
    'OIL': 'USO',
    'PETROLEO': 'USO',
};
